import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()

describe('webview run status indicator', () => {
  it('运行状态固定在顶栏槽位，生命周期变化不再增删独立状态行', () => {
    const source = readFileSync(join(root, 'webview-ui/src/App.tsx'), 'utf8')

    expect(source).toContain('function RunActivityIndicator')
    expect(source).toContain('function RunStatusDetails')
    expect(source).toContain("status === 'Running…'")
    expect(source).toContain("status === 'Completed'")
    expect(source).toContain('className={`run-indicator run-indicator--${activity.kind}`}')
    expect(source).toContain('aria-label={t(activity.label)}')
    expect(source).toContain('<EditedFilesSummary')
    expect(source).toContain('reviewActiveRun={reviewActiveRun}')
    expect(source).toContain('onResolveFile={onResolveFile}')
    expect(source).toContain('mergeEditedFileSummaries(editedFiles, reviewFiles)')
    expect(source).toContain("type: 'inlineDiff.open'")
    expect(source).toContain("type: 'inlineDiff.resolve'")
    expect(source).toContain("type: 'inlineDiff.dismiss'")
    expect(source).toContain("message.type === 'inlineDiff.state'")
    expect(source).toContain('<RunActivityIndicator status={runStatus} />')
    expect(source).toContain('<RunStatusDetails')
    expect(source).toContain('const message = status && !getRunActivity(status) ? status : null')
    expect(source).toContain('const isSessionChange = sessionId !== selectedSessionIdRef.current')
    expect(source).toContain('if (isSessionChange && !isRunningRef.current)')
    expect(source).toContain('setReviewFiles([])')
    expect(source).toContain('onPointerDownCapture={clearSettledRunIndicator}')
    expect(source).toContain('onKeyDownCapture={clearSettledRunIndicator}')
    expect(source).toContain('function QuestionBanner')
    expect(source).toContain("type: 'question.reply'")
    expect(source).toContain("type: 'question.reject'")
    expect(source).toContain('<QuestionBanner pending={pendingQuestion} onReply={requestQuestionReply} onReject={requestQuestionReject} />')
    expect(source).not.toContain('{runStatus ? <p className="status-line">{runStatus}</p> : null}')
    expect(source).not.toContain('{loadingTranscript ? <p className="empty-line">Loading')
    expect(source).not.toContain("t('No messages')")
  })

  it('样式层提供运行 spinner 与完成勾选动画', () => {
    const styles = readFileSync(join(root, 'webview-ui/src/styles.css'), 'utf8')

    expect(styles).toContain('.run-indicator--running .run-indicator__icon')
    expect(styles).toContain('.run-activity-slot')
    expect(styles).toContain('flex: 0 0 1.75rem')
    expect(styles).toContain('.run-activity-slot.is-empty')
    expect(styles).toContain('visibility: hidden')
    expect(styles).toContain('animation: run-status-spin')
    expect(styles).toContain('.run-indicator--completed .run-indicator__icon::after')
    expect(styles).toContain('animation: run-status-check')
    expect(styles).toContain('@keyframes run-status-spin')
    expect(styles).toContain('@keyframes run-status-check')
    expect(styles).toContain('translate(-50%, -50%) rotate(45deg)')
    expect(styles).toContain('.edit-summary__item')
    expect(styles).toContain('.edit-summary__action-button')
    expect(styles).toContain('.edit-summary__action-button--reject')
    expect(styles).toContain('.edit-summary__item--unavailable')
    expect(styles).toContain('--edit-summary-row-height: 3.75rem;')
    expect(styles).toContain('grid-auto-rows: var(--edit-summary-row-height);')
    expect(styles).toContain('overflow-y: auto;')
    expect(styles).toContain('overscroll-behavior: contain;')
    expect(styles).toContain('grid-template-columns: minmax(0, 1fr);')
    expect(styles).toContain('inset-inline: 0;')
    expect(styles).toContain('overflow-wrap: anywhere;')
    expect(styles).toContain('flex-wrap: wrap;')
    expect(styles).toMatch(/\.run-status-row\s*\{[^}]*flex: 0 0 auto;/s)
    expect(styles).toContain('.question-banner')
    expect(styles).toContain('.question-banner__option')
  })
})
